### ISSUE TITLE
The contents of the tap files are written into the build.xml file causing high CPU usage

### ISSUE THREAD

**Issue by mihai-dinu** [kinow/tap-plugin#3]
**Problem:** We have a job that runs 100+ tests which output quite a lot of debug data in the tap file. Once the history reached 100 jobs, our Jenkins instance started to feel slow and had high CPU usage most of the time. After investigating what kept the CPU busy, we concluded that it is because it was parsing very big (12-18MB) build.xml files. 
These build.xml files contained all the output from the tap files in them, making them around 200,000 lines long. 

Searching around, there are some other issues that point to the same problem: 
https://issues.jenkins-ci.org/browse/JENKINS-20212
https://github.com/nodejs/build/issues/453 

**Plugin version:** 2.1

**Comment by mihai-dinu** [comment]
@kinow if you are ok with it, I would like to look into the problem and try to fix it. Do you have any inside information that I should know about before I start looking into the problem?

**Comment by kinow** [comment]
Hi @mihai-dinu a proper re-written is long due. The initial version was a POC to see if Jenkins could support TAP, and it was my first time using the Jenkins tests API (before the JUnit plug-in came out of the core).

So there's lot of room for improvement, though I suspect the changes are not so small.

If you find a simple change to improve it, feel free to submit a pull request. If you'd prefer to work on a major change, I'd be keen to help with that as well. There's an old ticket somewhere about performance issues, regarding memory, which could be fixed with a better management of objects & data by the plugin.
